stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

test:unit:
  stage: test
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 60
    - echo "Code coverage is 90%"

deploy-staging:
  stage: deploy
  environment:
    name: staging
  script:
    - echo "Deploying to staging..."
    - echo "Successfully deployed to staging"

deploy-production:
  stage: deploy
  environment:
    name: production
  when: manual
  script:
    - echo "Deploying to production..."
    - echo "Successfully deployed to production"
