default:
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - chmod 400 "$EC2_SSH_KEY"
    - ssh-add "$EC2_SSH_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

test:unit:
  stage: test
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 60
    - echo "Code coverage is 90%"

deploy-staging:
  stage: deploy
  environment:
    name: staging
  script:
    - echo "Deploying to staging..."
    - echo "Successfully deployed to staging"

deploy-production:
  stage: deploy
  environment:
    name: production
  when: manual
  script:
    - echo "Deploying to production..."
    - echo "Successfully deployed to production"
